version: "3.8"
services:
#  rabbitmq:
#    image: rabbitmq:3.9.7-management-alpine
#    hostname: rabbitmq
#    container_name: rabbitmq
#    ports:
#      - 15672:15672
#      - 5672:5672
#    environment:
#      RABBITMQ_DEFAULT_USER: admin
#      RABBITMQ_DEFAULT_PASS: admin
#    volumes:
#      - ./data/dev/rabbitmq:/var/lib/rabbitmq
#    networks:
#      - internal
#    healthcheck:
#      test: rabbitmq-diagnostics -q ping
#      interval: 30s
#      timeout: 30s
#      retries: 3
#    restart: always
#  pg.order:
#    image: postgres:13.5-alpine
#    container_name: postgresql.order
#    hostname: postgresql
#    ports:
#      - 5432:5432
#    environment:
#      POSTGRES_USER: pg-order
#      POSTGRES_PASSWORD: pg-order
#      #POSTGRES_DB: dev
#      POSTGRES_HOST_AUTH_METHOD: trust
#    networks:
#      - internal
#    volumes:
#      - ./docker/dev/pg-order.sql:/docker-entrypoint-initdb.d/init.sql
#      - ./data/dev/pg-order:/var/lib/postgresql/data
#    healthcheck:
#      test: ["CMD-SHELL", "pg_isready -U postgres"]
#      interval: 10s
#      timeout: 5s
#      retries: 5
#    command: postgres -c stats_temp_directory=/tmp

  php:
    build: "docker/dev/php"
    container_name: php
    hostname: php
    ports:
      - 8081:8080
    env_file:
      - .env
    volumes:
      - ./order-ms/:/app
    working_dir: /app
    networks:
      - internal
    extra_hosts:
      - "host.docker.internal:host-gateway"
#   depends_on:
#     - pg.order
#     - rabbitmq

#возможно, у меня падает nginx, т.к. имя хоста не указана на контейнере пхп-фпма
  nginx:
    image: nginx:1.21.3-alpine
    container_name: nginx
    hostname: nginx
    volumes:
      - ./docker/dev/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./order-ms:/app
      - ./docker/dev/nginx/php-fpm:/etc/nginx/php-fpm
#    depends_on:
#      - app_order
    restart: always
    ports:
      - 80:80
      #- 8081:80
    networks:
      - internal
networks:
  internal:
    name: ms1
